### PR TITLE
Expose PatternFilterable for extra include/exclude configurations

### PR DESCRIPTION
**Pull request by vlsi**

### CODE REVIEW

**Comment by eskatos** [comment]
This is a good idea. Some coverage would help pushing this to a mergeable state.

**Comment by vlsi** [comment]
@eskatos , by the way, I have implemented `.gitignore to Spec<FileTreeElement>` (e.g. https://github.com/vlsi/vlsi-release-plugins/blob/53a3fd2272566f3468d1045e78bb0838cd3daf62/plugins/crlf-plugin/src/main/kotlin/com/github/vlsi/gradle/git/dsl/FilterExtensions.kt#L32 ), so I like this PR better than #10 

Will add tests soon.

**Comment by vlsi** [comment]
@eskatos , could you please clarify what do you mean by "Some coverage"?

It turns out this PR does update the test so the test coverage is there. I don't think we should test `PatternSet` itself as it is expected to be tested by Gradle.

PS. As I was updating the documentation, I thought about making `RatTask implements PatternFilterable`
What do you think?

```groovy
open class RatTask private constructor(
        private val patternSet: PatternSet,
        private val workerExecutor: WorkerExecutor
) : DefaultTask(), PatternFilterable by patternSet {

    @Inject constructor(
        workerExecutor: WorkerExecutor
    ): this(PatternSet(), workerExecutor)
```
 
It is in line with in-core `AbstractCopyTask`.
The sad thing is then `RatTask#excludes` clashes with `PatternFilterable#getExcludes/setExcludes`.

Frankly speaking I'm inclined to `RatTask implements PatternFilterable` approach and removal of the current `val excludes = project.objects.listProperty<String>()`

**Comment by vlsi** [comment]
It turns out `RatTask implements PatternFilterable` is nice: it seems to support both old and new syntax more-or-less transparently.

Looking forward to creadur-rat-gradle 0.5.0

**Comment by eskatos** [comment]
It'll be a breaking change for scripts doing e.g. `excludes.set(listOf("foo", "bar"))`. But I think it's fine given the `0.x` version number and the good enhancement!

Coverage is fine, some is missing but has nothing to do with this change.

Thank you for the PR @vlsi! 

I just updated the `master` branch with coverage for new Gradle versions and more strict task annotation checks. Could you please rebase your branch on top of `master`?

**Comment by vlsi** [comment]
> Could you please rebase your branch on top of master?

@eskatos , done. Travis test passes now.

PS. Gradle might want to be smarter for cases like `Task implements PatternFilterable =that means=> getIncludes and getExcludes are @Internal`

**Comment by eskatos** [comment]
Perfect, thanks @vlsi!

**Comment by eskatos** [comment]
`0.5.0` published ✅ 
https://plugins.gradle.org/plugin/org.nosphere.apache.rat

**Pull request merged**
